### ISSUE TITLE
An error when I run the train.py of LSTM-CNNs-CRF

### ISSUE THREAD

**Issue by yikedouer** [ne7ermore/torch_light#4]
Hi,I'm new to pytorch,when I run the train.py, I got error below, I try such ways to slove, bur all not work. How this error means,?Thanks.
`D:\workspace\Python\NLP\torch_light-master\LSTM-CNNs-CRF\model.py:158: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  init.xavier_uniform(self.char_ebd.weight)
D:\workspace\Python\NLP\torch_light-master\LSTM-CNNs-CRF\model.py:31: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  init.xavier_uniform(self.transitions)
D:\Program\Anaconda3\lib\site-packages\torch\cuda\__init__.py:116: UserWarning: 
    Found GPU0 Quadro K600 which is of cuda capability 3.0.
    PyTorch no longer supports this GPU because it is too old.
    
  warnings.warn(old_gpu_warn % (d, name, major, capability[1]))
Train Processing: 0it [00:00, ?it/s]------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "D:/workspace/Python/NLP/torch_light-master/LSTM-CNNs-CRF/train.py", line 148, in <module>
    loss = train()
  File "D:/workspace/Python/NLP/torch_light-master/LSTM-CNNs-CRF/train.py", line 130, in train
    loss, _ = model(word, char, label)
  File "D:\Program\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\workspace\Python\NLP\torch_light-master\LSTM-CNNs-CRF\model.py", line 187, in forward
    char_feats = self.cnn(chars)
  File "D:\Program\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\workspace\Python\NLP\torch_light-master\LSTM-CNNs-CRF\model.py", line 163, in forward
    encode = self.char_ebd(encode).unsqueeze(1)
  File "D:\Program\Anaconda3\lib\site-packages\torch\nn\modules\module.py", line 491, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Program\Anaconda3\lib\site-packages\torch\nn\modules\sparse.py", line 108, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "D:\Program\Anaconda3\lib\site-packages\torch\nn\functional.py", line 1076, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
RuntimeError: Expected tensor for argument #1 'indices' to have scalar type Long; but got CUDAIntTensor instead (while checking arguments for embedding)`

**Comment by ne7ermore** [comment]
Found GPU0 Quadro K600 which is of cuda capability 3.0.
**PyTorch no longer supports this GPU because it is too old.**

**Comment by yikedouer** [comment]
Thanks for  replying,but that isn't the problem. I shut down the cuda ,and the error still be there. Then I change the line38 of  model.py to below:

`    def _score_sentence(self, input, tags):
        bsz, sent_len, l_size = input.size()
        sco        re = Variable(self.torch.FloatTensor(bsz).fill_(0.))
        **s_score = Variable(self.torch.LongTensor([[START]] * bsz)).long()**
        tags = torch.cat([s_score, tags], dim=-1)
        input_t = input.transpose(0, 1)
`

The error is gone.You use pytorch0.2, and mine is pytorch 0.4,maybe there are some changes.
And I have another question, hoping not bother you:
in viterbi_decode() fuction,what's the meaning of the last element of variable best_path,the dimension shape of it is different from previous element,and that cause `torch.cat(best_path, dim=-1)` raise an error.
Traceback (most recent call last):
  File "D:/workspace/Python/NLP/torch_light-master/LSTM-CNNs-CRF/train.py", line 151, in <module>
    loss, corrects, acc, size = evaluate()
  File "D:/workspace/Python/NLP/torch_light-master/LSTM-CNNs-CRF/train.py", line 111, in evaluate
    pred = model.predict(word, char)
  File "D:\workspace\Python\NLP\torch_light-master\LSTM-CNNs-CRF\model.py", line 198, in predict
    return self.crf.viterbi_decode(out)
  File "D:\workspace\Python\NLP\torch_light-master\LSTM-CNNs-CRF\model.py", line 108, in viterbi_decode
    return torch.cat(best_path, dim=-1)
RuntimeError: invalid argument 0: Tensors must have same number of dimensions: got 2 and 1 at c:\users\administrator\downloads\new-builder\win-wheel\pytorch\aten\src\th\generic/THTensorMath.c:3577

I reshape it ,but the final result accuracy is always 0.00.
Thanks again.

**Comment by ne7ermore** [comment]
i have fixed the issue
please update the code and train again
my pt version is updated to 0.4.0

**Comment by yikedouer** [comment]
OK，it works well,thanks, : ))
