### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'data'

### ISSUE THREAD

**Issue by iblh** [ne7ermore/torch_light#7]
Trying to train the retrieval-based-chatbots.
There has an error.

Expect for your reply.
```
▶ python3 train.py
==============================arguments==============================
logdir: logdir
batch_size: 64
lr: 0.001
dropout: 0.5
emb_dim: 200
first_rnn_hsz: 200
fillters: 8
kernel_size: (3, 3)
match_vec_dim: 50
second_rnn_hsz: 50
use_cuda: False
max_cont_len: 10
max_utte_len: 50
dict_size: 156260
============================================================
Traceback (most recent call last):
  File "train.py", line 88, in <module>
    model = Model(args)
  File "/Users/viosey/Workspace/Dev/ML/PyTorch/torch_light/retrieval-based-chatbots/model.py", line 32, in __init__
    self._reset_parameters()
  File "/Users/viosey/Workspace/Dev/ML/PyTorch/torch_light/retrieval-based-chatbots/model.py", line 40, in _reset_parameters
    self.transform_A.bias.data.fill_(0)
AttributeError: 'NoneType' object has no attribute 'data'
```

**Comment by ne7ermore** [comment]
fixed this bug, plz try again.
