### ISSUE TITLE
Image-Cap: Assertion Error

### ISSUE THREAD

**Issue by metro-smiles** [ne7ermore/torch_light#8]
Hi,

@ne7ermore : So I get the following error when I try to load the actor model to the GPU (i.e. in train.py). Any help would be much appreciated.
`Traceback (most recent call last):
  File "train.py", line 114, in <module>
    actor = actor.cuda()
  File "/home/user/anaconda2/envs/py35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 216, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/user/anaconda2/envs/py35/lib/python3.5/site-packages/torch/nn/modules/module.py", line 146, in _apply
    module._apply(fn)
  File "/home/user/anaconda2/envs/py35/lib/python3.5/site-packages/torch/nn/modules/rnn.py", line 123, in _apply
    self.flatten_parameters()
  File "/home/user/anaconda2/envs/py35/lib/python3.5/site-packages/torch/nn/modules/rnn.py", line 111, in flatten_parameters
    params = rnn.get_parameters(fn, handle, fn.weight_buf)
  File "/home/user/anaconda2/envs/py35/lib/python3.5/site-packages/torch/backends/cudnn/rnn.py", line 165, in get_parameters
    assert filter_dim_a.prod() == filter_dim_a[0]
AssertionError
`

I checked to make sure that the library versions match with the requirements.

**Comment by ne7ermore** [comment]
may have at least one gpu

**Comment by metro-smiles** [comment]
So the issue was that I was trying to run it in PyTorch 0.3.1 but I found that it works with PyTorch 0.3.0. Please consider updating the README here: https://github.com/ne7ermore/torch-light/blob/master/Image-Cap/README.md

**Comment by ne7ermore** [comment]
> So the issue was that I was trying to run it in PyTorch 0.3.1 but I found that it works with PyTorch 0.3.0. Please consider updating the README here: https://github.com/ne7ermore/torch-light/blob/master/Image-Cap/README.md

i see, thank you!
